workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.traveltime.converter"

    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Build iOS IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        api_key: Codemagic
        submit_to_testflight: true

      email:
        recipients:
          - travel.time.converter@gmail.com
        notify:
          success: true
          failure: true
