const Map<String, String> currencyDescriptions = {
  'ARS': 'Argentine Peso',
  'AUD': 'Australian',
  'BOB': 'Bolivian Boliviano',
  'BSD': 'Bahamas',
  'BZD': 'Belize Dollar',
  'BRL': 'Brazil Real',
  'CAD': 'Canadian Dollar',
  'CLF': 'Chile',
  'CNY': 'Chinese Yuan',
  'COP': 'Colombian Peso',
  'CRC': 'Costa Rican Colon',
  'CUP': 'Cuban',
  'DKK': 'Danish',
  'DOP': 'Dominican Peso',
  'EGY': 'Egyptian',
  'EUR': 'Euro',
  'GTQ': 'Guatemalan Quetzal',
  'GYD': 'Guyanaese Dollar',
  'HNL': 'Honduran Lempira',
  'HKD': 'Hong Kong',
  'HUF': 'Hungarian',
  'INR': 'Indian',
  'ILS': 'Israeli New Sheqel',
  'JMD': 'Jamaican',
  'JPY': 'Japanese Yen',
  'MXN': 'Mexican Peso',
  'NIO': 'Nicaraguan Cordoba',
  'NOK': 'Norwegian',
  'PAB': 'Panamanian Balboa',
  'PEN': 'Peruvian Nuevo Sol',
  'PYG': 'Paraguayan Guarani',
  'GBP': 'British Pound',
  'RUB': 'Russian Ruble',
  'SVC': 'Salvadoran Colón',
  'SEK': 'Swedish',
  'SRD': 'Surinamese Dollar',
  'TTD': 'Trinidad and Tobago',
  'USD': 'US Dollar',
  'UYU': 'Uruguayan Peso',
  'VEF': 'Venezuelan Bolivar',
  'XCD': 'East Caribbean',
};
